/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Items Queue Demo 11/7/2025
 * Environment: Production
 * Id: 24eb7b70-0a8d-0165-ee04-51d6a07ea0ed
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Article' type
 */
export type ArticleTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article">

/*
 * Typeguard for codename of 'Article' type
 */
export function isArticleTypeCodename(value: string | undefined | null): value is ArticleTypeCodename {
  return typeof value === "string" && value === ("article" satisfies ArticleTypeCodename)
}

/*
 * Article
 *
 * Id: fd9c6f36-44d5-40a9-8b5f-5c7b0e5add30
 * Codename: article
 */
export type ArticleType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: 9ee55046-1db7-4233-99a8-93445150b289
     * Type: text
     * Required: false
     */
    readonly title: Elements.TextElement

    /*
     * Text
     *
     * Codename: text
     * Id: e3a982f7-a280-4919-b230-10b9b2d61df9
     * Type: text
     * Required: false
     */
    readonly text: Elements.TextElement

    /*
     * Queue Assigned
     *
     * Codename: queue_assigned
     * Id: a7acbe9f-eb2a-45ec-bedb-37bce06a3934
     * Type: multiple_choice
     * Required: false
     */
    readonly queue_assigned: Elements.MultipleChoiceElement<ArticleTypeQueueAssignedMultipleChoiceOptions>
  },
  ArticleTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Article
 */
export type ArticleTypeElementCodenames = "title" | "text" | "queue_assigned"

/*
 * Type guard for Article
 *
 * Id: fd9c6f36-44d5-40a9-8b5f-5c7b0e5add30
 * Codename: article
 */
export function isArticleType(item: IContentItem | undefined | null): item is ArticleType {
  return item?.system.type === ("article" satisfies ArticleTypeCodename)
}

export type ArticleTypeQueueAssignedMultipleChoiceOptions = "true" | "false"
