/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Items Queue Demo 11/7/2025
 * Environment: Production
 * Id: 24eb7b70-0a8d-0165-ee04-51d6a07ea0ed
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all collection codenames
 */
export const collectionCodenames = ["default"] as const

/*
 * Type representing all collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number]

/*
 * Typeguard for collection codename
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
  return typeof value === "string" && (collectionCodenames as readonly string[]).includes(value)
}
