/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Items Queue Demo 11/7/2025
 * Environment: Production
 * Id: 24eb7b70-0a8d-0165-ee04-51d6a07ea0ed
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = [] as const

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number]

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
  return typeof value === "string" && (taxonomyCodenames as readonly string[]).includes(value)
}
