/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Items Queue Demo 11/7/2025
 * Environment: Production
 * Id: 24eb7b70-0a8d-0165-ee04-51d6a07ea0ed
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default", "bla"] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
  return typeof value === "string" && (workflowCodenames as readonly string[]).includes(value)
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = [
  "draft",
  "published",
  "archived",
  "scheduled",
  "draft_221b410",
  "unassigned",
  "in_progress",
] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
  return typeof value === "string" && (workflowStepCodenames as readonly string[]).includes(value)
}
