/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Items Queue Demo 11/7/2025
 * Environment: Production
 * Id: 24eb7b70-0a8d-0165-ee04-51d6a07ea0ed
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Default' collection
 */
export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">

/*
 * Typeguard for codename of 'Default' collection
 */
export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultCollectionCodename)
}
